### ISSUE TITLE
Migrate out of Gridsome

### ISSUE THREAD

**Issue by Thog** [Ryujinx/Ryujinx-Website#12]
Gridsome has been mostly left abandoned for the past year, it might be worth migrating to another solution like Nuxt.

**Comment by yoshiyes** [comment]
Hello. 

I thing we need to :
- Upgrade to Vue 3
- Remove Grindsome and use native vue project
- Migrate to Vite builder (fast build and less annoying then webpack config)

Actually, the website can't be updated to latest vue version., the ui library( Vuetify ) only have beta version and he didn't seem to be stable.

So we can drop Vuetify and use TailwindCSS (or any simple CSS framework).

I can build a new website from scratch and keep all the information of the original website.

**Comment by AcK77** [comment]
That could be nice, it could useful if we could include some pages of the wiki of our main repo too, (like guides or something) but that probably needs to use the GitHub API.

Our compatibility list needs some life if you want too (we have nothing and use GitHub issue)
