### ISSUE TITLE
API rate limit exceeded for {IP}

### ISSUE THREAD

**Issue by JounQin** [Ryujinx/Ryujinx-Website#30]
https://api.github.com/repos/Ryujinx/release-channel-master/releases/latest

```json
{
    "message": "API rate limit exceeded for {IP}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

**Comment by TSRBerry** [comment]
Without a description, this is useless. Feel free to reopen after providing some info.

**Comment by JounQin** [comment]
@TSRBerry 

<img width="1726" alt="image" src="https://github.com/Ryujinx/Ryujinx-Website/assets/8336744/1d51ac49-5ac1-4a5d-b2e9-4b84f130ad62">

https://ryujinx.org/download does not load correctly due to the xhr error.
